sudo: required
dist: xenial
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
    #- "3.8-dev"
install:
  - pip install lxml
  - pip install coverage
  - pip install pytest-cov
  - pip install flake8
  - pip install codecov
  - pip install -r requirements.txt
  - sudo apt-get install pandoc
before_script:
  - "flake8 ."
script:
  - py.test --cov=testrunner tests/
after_success:
  - coverage combine
  - coverage report
  - coverage xml
  - if [ ! -z "$CODECOV_TOKEN" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.6" ] && [ "$TRAVIS_BRANCH" == "master" ]; then codecov; fi
notifications:
  email:
    - python-test-runner@googlegroups.com
