sudo: required
dist: xenial
language: python
cache: pip
matrix:
  include:
    - os: linux
      sudo: required
      python: 3.6
      env: TOXENV=py36
    - os: linux
      sudo: required
      python: 3.7
      env: TOXENV=py37
    - os: linux
      sudo: required
      python: "3.8-dev"
      env: TOXENV=py38-dev
    - os: osx
      language: generic
      env: TOXENV=py37
install:
  - pip install tox
  - pip install lxml
  - pip install coverage
  - pip install pytest-cov
  - pip install flake8
  - pip install codecov
  - pip install -r requirements.txt
  - sudo apt-get install pandoc
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.8-dev" ]]; then flake8 .; fi
script:
  - py.test --cov=testrunner tests/
after_success:
  - coverage combine
  - coverage report
  - coverage xml
  - if [ ! -z "$CODECOV_TOKEN" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.6" ] && [ "$TRAVIS_BRANCH" == "master" ]; then codecov; fi
notifications:
  email:
    - python-test-runner@googlegroups.com
