language: python
python:
  - "3.6"
  - "3.7-dev"
install:
  - pip install lxml
  - pip install coverage
  - pip install pytest-cov
  - pip install flake8
  - pip install -r requirements.txt
  - travis_retry pip install -e git+https://github.com/codacy/python-codacy-coverage.git#egg=codacy
  - sudo apt-get install pandoc
before_script:
  - "flake8 --ignore=F401 ."
script:
  - py.test --cov=testrunner tests/
after_success:
  - coverage combine
  - coverage report
  - coverage xml
  - if [ ! -z "$CODACY_PROJECT_TOKEN" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.6" ] && [ "$TRAVIS_BRANCH" == "master" ]; then python-codacy-coverage -r coverage.xml; fi
notifications:
  email:
    - python-test-runner@googlegroups.com
